FROM node:25-alpine

WORKDIR /app

COPY package.json /app/
RUN npm install

COPY . .
RUN npm run build

# COPY --from=builder /app/node_modules /app/node_modules
EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]