FROM oven/bun:latest AS builder

WORKDIR /app

COPY package.json bun.lock /app/
RUN bun install

COPY . .
RUN bun run build

FROM node:25-alpine AS production
WORKDIR /app

COPY --from=builder /app/.output /app/.output
COPY --from=builder /app/node_modules /app/node_modules
EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]